name: ksmessaging
description: Ks-messaging private chat application.

dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.1.1
  google_sign_in: 0.3.1
  firebase_analytics: 0.0.4
  firebase_auth: 0.2.0
  firebase_database: 0.0.12
  firebase_storage: 0.0.5

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png