name: ksmessaging
description: Ks-messaging private chat application.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_database: ^11.0.0
  firebase_analytics: ^11.0.0
  firebase_messaging: ^15.0.0
  firebase_ai: ^3.0.0
  flutter_ai_toolkit: ^0.9.0
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.1
  image_picker: ^1.0.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png